services:

  frontend:
    build: ./frontendkelsia
    ports:
      - "8082:8082"
    depends_on:
      - backend
    networks:
      - app-net
      
  backend:
    build: ./backendkelsia
    ports:
      - "8081:8081"
    env_file:
      - ./backendkelsia/.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-net

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: sistema_reservas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net: