server {
    listen 8082;
    location /api/ {
    proxy_pass http://backend:8081;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
    location /api/ {
        resolver 10.0.0.4 valid=30s;
        set $backend http://backend:8081;
        proxy_pass $backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}